In [1]:
import pandas as pd
import numpy as np
import pickle
from preprocessor import preprocessor
from config import pathconfig

In [2]:
def load_pkl(pkl_file):
    with open(pkl_file, 'rb') as inp:
        print(f"loading pickle file: {pkl_file}")
        pickled_obj = pickle.load(inp)
    return pickled_obj

In [4]:
if pathconfig.PRE_PKL_PATH.is_file():
    print('Loading PKL file...')
    pre = load_pkl(pathconfig.PRE_PKL_PATH)
    print('Successfully Loaded Pickle file')
else:
    print("NO PICKLE FILE FOUND SAD :(")

Loading PKL file...
loading pickle file: /home/prixa-ml/Desktop/projects/recommendation_news_api/repository/data-processing/processed_data/train_data/pre.pkl
Successfully Loaded Pickle file


In [5]:
pre.df

,user,url,additional_images,content,date,head_image,heading,label,source,author,...,all_heading_content,keywords,Dominant_Topic,final_rating,user_index,url_index,label_index,article_id,user_keywords,keywords_words
0,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
1,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
2,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
3,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
4,db783e901db42f2290736d314d08bdea,https://www.ratopati.com/story/94744,['https://ratopati.prixa.net/media/albums/666_...,['नेपाल राष्ट्र बैंकका अनुसार आज (साउन ७) एक अ...,2076-04-07 00:00:00+05:45,https://ratopati.prixa.net/media/albums/Exchan...,यस्तो छ आजको विनिमयदरः अमेरिकी डलरदेखि कतारी र...,अर्थ,ratopati,रातोपाटी संवाददाता,...,यस्तो विनिमयदरः अमेरि कतारी रियालसम्म नेपाल रा...,"[13073, 27456, 12617, 6083, 31465, 19698, 1293...",1,2.723818,158790,31534,2,ekuIAXIip3isHjFZAdmOs2rgb4KgToUZSIvURG0_AoA,"[पैसा, रुपैयाँ, बिक्रीदर, खरिददर, कतारी, विनिम...",पैसा रुपैयाँ बिक्रीदर खरिददर कतारी विनिमयदरः अ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707192,5cb16210f5bc5f18bb852ab846f3b5a2,https://www.thahakhabar.com/news/127679,[],['\xa0नेकपा एमालेका अध्यक्ष एवं प्रधानमन्त्री ...,2078-02-24 00:00:00+05:45,https://thahacdn.prixacdn.net/media/albums/Kha...,खनाल-नेपाल समूहका नेता सरकारमा सहभागी हुँदै !,राजनीति,thahakhabar,थाहा संवाददाता,...,खनाल-नेपाल समूह नेता सरकार सहभागी नेकपा एमाल अ...,"[13635, 1725, 19919, 25420, 8942, 5742, 31687,...",11,2.876623,67476,35675,22,1GFRtO4g4f79IRJjGdkvTisLdsMCtpQsVWBFDaW0Vec,"[खनाल–नेपाल, समूह, मन्त्रालय, मन्त्रिमण्डल, प्...",खनाल–नेपाल समूह मन्त्रालय मन्त्रिमण्डल प्रधानम...
707193,93c95988ec06dc1569a02ccb931c43a4,https://www.thahakhabar.com/news/127379,[],[

In [6]:
user_article_df = pre.df.groupby(['user','article_id']).size().reset_index(name='counts')

In [7]:
user_article_df

,user,article_id,counts
0,00003762db942cabd188b2984897e5c5,-t9eOCDALMucuwV2anKqozC3tKAJPJXK-FYX0yL6uto,4
1,00005513d5d145d61be64de14ab4b56e,0fFgohtzm1xbj8eb-qDaU2XEJJB3shhvq07MRWqoNGg,1
2,00005513d5d145d61be64de14ab4b56e,QvOcSQ3x4yVCj07VmcUwk2iSrD4dMQ6B0yrtCuoDAj4,1
3,0002eabd63d3cde55b2c77f2dcaa6ce0,GdqxyopGvEs7ndRXEtH0GtmX4a_vgdhvdfGtqhNH9xI,1
4,0002eabd63d3cde55b2c77f2dcaa6ce0,HNBPiTG8hyM8bs1W_GKER_tdE4dd9Ig6GBwQ66RbA-w,1
...,...,...,...
490290,fffe89d5e23fe936c45214fd1c52a7ce,5VAQKLW_L3Xje6Hd_8k4FECtuSeQnmQlp7VsEGFPB64,1
490291,fffec3687bd49131897f5f0d9e004e31,ga1Kpr2EWNJcqLorPh0ACPIuevssUKBA1bmzNr_ZRu0,1
490292,ffff938c69315daed47dc99398d9d15f,3cGFjHk7a41UgR85sGD0CFHKELDnVApKiaSgZuDQTOg,1
490293,ffffbed8db2a2fdd7e42372934f42cf2,BIy9ldQSOZM4OaxxavJm96FB1j2vmE0ZmHM2SZzrROs,1


In [8]:
data = user_article_df.dropna()
data = data.copy()

In [9]:
data.rename(columns={"article_id": "article", "counts": "views"},inplace=True)

In [10]:
data

,user,article,views
0,00003762db942cabd188b2984897e5c5,-t9eOCDALMucuwV2anKqozC3tKAJPJXK-FYX0yL6uto,4
1,00005513d5d145d61be64de14ab4b56e,0fFgohtzm1xbj8eb-qDaU2XEJJB3shhvq07MRWqoNGg,1
2,00005513d5d145d61be64de14ab4b56e,QvOcSQ3x4yVCj07VmcUwk2iSrD4dMQ6B0yrtCuoDAj4,1
3,0002eabd63d3cde55b2c77f2dcaa6ce0,GdqxyopGvEs7ndRXEtH0GtmX4a_vgdhvdfGtqhNH9xI,1
4,0002eabd63d3cde55b2c77f2dcaa6ce0,HNBPiTG8hyM8bs1W_GKER_tdE4dd9Ig6GBwQ66RbA-w,1
...,...,...,...
490290,fffe89d5e23fe936c45214fd1c52a7ce,5VAQKLW_L3Xje6Hd_8k4FECtuSeQnmQlp7VsEGFPB64,1
490291,fffec3687bd49131897f5f0d9e004e31,ga1Kpr2EWNJcqLorPh0ACPIuevssUKBA1bmzNr_ZRu0,1
490292,ffff938c69315daed47dc99398d9d15f,3cGFjHk7a41UgR85sGD0CFHKELDnVApKiaSgZuDQTOg,1
490293,ffffbed8db2a2fdd7e42372934f42cf2,BIy9ldQSOZM4OaxxavJm96FB1j2vmE0ZmHM2SZzrROs,1


In [11]:
# Create a numeric user_id and article_id column
data['user'] = data['user'].astype("category")
data['article'] = data['article'].astype("category")
data['user_id'] = data['user'].cat.codes
data['article_id'] = data['article'].cat.codes

In [12]:
len(data['article'].unique()), len(data['article_id'].unique())

(38054, 38054)

In [13]:
len(data['user'].unique()), len(data['user_id'].unique())

(185317, 185317)

In [14]:
data

,user,article,views,user_id,article_id
0,00003762db942cabd188b2984897e5c5,-t9eOCDALMucuwV2anKqozC3tKAJPJXK-FYX0yL6uto,4,0,570
1,00005513d5d145d61be64de14ab4b56e,0fFgohtzm1xbj8eb-qDaU2XEJJB3shhvq07MRWqoNGg,1,1,1041
2,00005513d5d145d61be64de14ab4b56e,QvOcSQ3x4yVCj07VmcUwk2iSrD4dMQ6B0yrtCuoDAj4,1,1,16532
3,0002eabd63d3cde55b2c77f2dcaa6ce0,GdqxyopGvEs7ndRXEtH0GtmX4a_vgdhvdfGtqhNH9xI,1,2,10504
4,0002eabd63d3cde55b2c77f2dcaa6ce0,HNBPiTG8hyM8bs1W_GKER_tdE4dd9Ig6GBwQ66RbA-w,1,2,10911
...,...,...,...,...,...
490290,fffe89d5e23fe936c45214fd1c52a7ce,5VAQKLW_L3Xje6Hd_8k4FECtuSeQnmQlp7VsEGFPB64,1,185312,3849
490291,fffec3687bd49131897f5f0d9e004e31,ga1Kpr2EWNJcqLorPh0ACPIuevssUKBA1bmzNr_ZRu0,1,185313,26484
490292,ffff938c69315daed47dc99398d9d15f,3cGFjHk7a41UgR85sGD0CFHKELDnVApKiaSgZuDQTOg,1,185314,2781
490293,ffffbed8db2a2fdd7e42372934f42cf2,BIy9ldQSOZM4OaxxavJm96FB1j2vmE0ZmHM2SZzrROs,1,185315,7298


In [15]:
import scipy.sparse as sparse
from scipy.sparse.linalg import spsolve
import random
from sklearn.preprocessing import MinMaxScaler


In [16]:
# The implicit library expects data as a item-user matrix so we
# create two matricies, one for fitting the model (item-user) 
# and one for recommendations (user-item)
sparse_item_user = sparse.csr_matrix((data['views'].astype(float), (data['article_id'], data['user_id'])))
# sparse_user_item = sparse.csr_matrix((data['views'].astype(float), (data['user_id'], data['article_id'])))


In [17]:
from implicit.nearest_neighbours import bm25_weight
sparse_user_item = sparse_item_user.T.tocsr()

In [18]:
sparse_item_user,sparse_user_item

(<38054x185317 sparse matrix of type '<class 'numpy.float64'>'
 	with 490295 stored elements in Compressed Sparse Row format>,
 <185317x38054 sparse matrix of type '<class 'numpy.float64'>'
 	with 490295 stored elements in Compressed Sparse Row format>)

In [19]:
from implicit.als import AlternatingLeastSquares

model = AlternatingLeastSquares(factors=64, regularization=0.05)
model.fit(2 * sparse_user_item)

  0%|          | 0/15 [00:00<?, ?it/s]

In [31]:
user_id_dict = pd.Series(data.user_id.values, index=data.user).to_dict()
user_id_dict

{'00003762db942cabd188b2984897e5c5': 0,
 '00005513d5d145d61be64de14ab4b56e': 1,
 '0002eabd63d3cde55b2c77f2dcaa6ce0': 2,
 '000319e51abbb8b7845aa9458a76a008': 3,
 '0003b1b5cc4f651143a263fc1ad72f65': 4,
 '0003d0b819f28410136a64f9e4737211': 5,
 '000419ff83e2c85b965664051c2e0407': 6,
 '00048e6368b0ae8148361fa73a3a7ec7': 7,
 '0004b6c117d624c8568555355800395c': 8,
 '0005d54e85dfbb09fae7c60d6c6d2e97': 9,
 '0005d9b1e772a8e2157e23c4021dc406': 10,
 '0005f0af3015fd96528c2ac114d6268a': 11,
 '00060ec9ad3cdf33b917a16ed2025f95': 12,
 '00066712f0816e665ff5802594966fad': 13,
 '000675d8f62da0ed6608f9bd20cbc17e': 14,
 '0006b43202ab780dc35651ad251372c6': 15,
 '0006be6c307a219c99a098a1cbe742f2': 16,
 '000704e7c396dfdbeba05fdc7a4d9b24': 17,
 '0007872047ce09c541c71deb047d1fb1': 18,
 '0007d2b364bd119f1a541ed0ff1a2025': 19,
 '000832d61b2563a12ea9403e478aa769': 20,
 '000891a8f8b71bd28108553a67062344': 21,
 '0008d4175965bad7a17a7a662ca38e9e': 22,
 '0009469f3a744eb8b32418d4e45cc0be': 23,
 '000946ef4c43c478afe75f68

In [32]:
user_id_dict.get('0002eabd63d3cde55b2c77f2dcaa6ce0')

2

In [21]:
# Get recommendations for the a single user
userid = 12345
ids, scores = model.recommend(userid, sparse_user_item[userid], N=10, filter_already_liked_items=False)

In [22]:
ids, scores

(array([  748, 24685, 25728,   618, 31676, 20165, 26469, 11180, 20098,
        24043], dtype=int32),
 array([1.0415375 , 0.93676543, 0.6259685 , 0.5555456 , 0.52751076,
        0.51951224, 0.47814673, 0.46559575, 0.42275968, 0.40004197],
       dtype=float32))

In [24]:
for id in ids:
    print(f"id is : {id}")
    article_id = data.article.loc[data.article_id == id].iloc[0]
    print(f"article_id is : {article_id}")
    article_url = pre.article_df.url.loc[pre.article_df.article_id == article_id].iloc[0]
    print(f"article_url is : {article_url}")
    print(article_url)

id is : 748
article_id is : 0CzbYaKU_rjkm9ddwIr3Xehls7k4a6ohdB2sgkvQMLg
article_url is : https://www.ratopati.com/story/151779
https://www.ratopati.com/story/151779
id is : 24685
article_id is : dhsWwaBXwHxX3ORdRK3w1PehCFc5lC3U3RMGpgLf6Tk
article_url is : https://www.ratopati.com/story/149970
https://www.ratopati.com/story/149970
id is : 25728
article_id is : fMrzWpiWyYm4JKSJvHSwGQRDybfB_HauC_eCvXilYrg
article_url is : https://www.ratopati.com/story/141729
https://www.ratopati.com/story/141729
id is : 618
article_id is : -yuYUjmARhuYM0XPZzCkSCA0KN5T9m9FU0_peb_Uemk
article_url is : https://www.ratopati.com/story/142715
https://www.ratopati.com/story/142715
id is : 31676
article_id is : pM2UeEnAa_74tgSz8hAtq2o_n3_iV0R52g36m4MaOMw
article_url is : https://www.ratopati.com/story/150087
https://www.ratopati.com/story/150087
id is : 20165
article_id is : XAo-LBYnPGOft-Cw8FqmT0x1ABNachyKp5PJDffOkdI
article_url is : https://www.ratopati.com/story/153880
https://www.ratopati.com/story/153880
id

In [33]:
article_list = [pre.article_df.url.loc[pre.article_df.article_id == data.article.loc[data.article_id == id].iloc[0]].iloc[0] for id in ids]

In [34]:
article_list

['https://www.ratopati.com/story/100002',
 'https://www.ratopati.com/story/99687',
 'https://www.ratopati.com/story/107586',
 'https://www.ratopati.com/story/99658',
 'https://www.ratopati.com/story/109291',
 'https://www.ratopati.com/story/96483',
 'https://www.ratopati.com/story/99363',
 'https://www.ratopati.com/story/97844',
 'https://www.ratopati.com/story/99308',
 'https://www.ratopati.com/story/116201']

In [25]:
# get related items for the beatles (itemid = 25512)
ids, scores= model.similar_items(5555)

# display the results using pandas for nicer formatting
# pd.DataFrame({"artist": artists[ids], "score": scores})

In [27]:
ids, scores

(array([32163,  5555, 19827,  4157, 12444, 11860,  7642, 16884, 32752,
         2286], dtype=int32),
 array([0.99999994, 0.99999994, 0.9999998 , 0.99999785, 0.99999434,
        0.99994934, 0.9924626 , 0.9910785 , 0.99055636, 0.9739194 ],
       dtype=float32))

In [26]:
for id in ids:
    print(f"id is : {id}")
    article_id = data.article.loc[data.article_id == id].iloc[0]
    print(f"article_id is : {article_id}")
    article_url = pre.article_df.url.loc[pre.article_df.article_id == article_id].iloc[0]
    print(f"article_url is : {article_url}")
    print(article_url)

id is : 32163
article_id is : q8ezYzI-6lm9PLFAG5qAgsyKqgCJTR1yWOa07QPYaJ8
article_url is : https://www.ratopati.com/story/100002
https://www.ratopati.com/story/100002
id is : 5555
article_id is : 8N-b4NU6ctSt19zPRASQIwqjO7cwuqt0-EgB0ZsodI4
article_url is : https://www.ratopati.com/story/99687
https://www.ratopati.com/story/99687
id is : 19827
article_id is : Wd8uhu5FR1Ww7_0PeA3r536olVJsG_9Gn1GejsYK-_s
article_url is : https://www.ratopati.com/story/107586
https://www.ratopati.com/story/107586
id is : 4157
article_id is : 5zefPW4RKW1d7YAYIFcuzEOru89C2VVny1YcxLhRYnY
article_url is : https://www.ratopati.com/story/99658
https://www.ratopati.com/story/99658
id is : 12444
article_id is : JzrtafoOkcTVcU17BOcjHJg1pG0rM1u9FB3Ud4GxAco
article_url is : https://www.ratopati.com/story/109291
https://www.ratopati.com/story/109291
id is : 11860
article_id is : J1VCGQom78fsbQlhY2SCKqgGybWIzXiijYAalamGPh0
article_url is : https://www.ratopati.com/story/96483
https://www.ratopati.com/story/96483
id is 